---
title: "Assignment"
author: "Nouran Attia"
output: html_document
---

Loading the data and splitting it into 85% training samples and 15% testing samples
```{r}
sonar.data <- read.csv("sonar.all-data", sep = ",")
names(sonar.data)[ncol(sonar.data)] <- "category"
train_size <- floor(0.85 * nrow(sonar.data))

set.seed(123)
train_ind <- sample(seq_len(nrow(sonar.data)), size = train_size)

train.data <- sonar.data[train_ind, ]
test.data <- sonar.data[-train_ind, ]
library(RWeka)
library(caret)
```
C4.5 Classifier
```{r, CACHED = TRUE}
model.C4.5 <- J48(category~.,data = sonar.data)
summary(model.C4.5)
C4.5_folds_eval <- evaluate_Weka_classifier(model.C4.5, numFolds = 10)
C4.5_folds_eval
```
Pruned C4.5 Classifier
```{r, CACHED = TRUE}
# pruned C4.5
model.pruned.C4.5 <- PART(category~.,data = sonar.data)
# summarize the fit
summary(model.pruned.C4.5)
C4.5_pruned_folds_eval <- evaluate_Weka_classifier(model.pruned.C4.5, numFolds = 10)
C4.5_pruned_folds_eval
```
Random Forest
```{r, CACHED = TRUE}
model <- train(train.data[,-61], train.data[,61],
                 method = "rf",
                 trControl = trainControl(method = "cv", number = 10, summaryFunction = defaultSummary))
predictions <- predict(model$finalModel, test.data)
results.matrix <- confusionMatrix(predictions , test.data$category)
tp <- results.matrix$table[1,1]
tn <- results.matrix$table[2,2]
fp <- results.matrix$table[1,2]
fn <- results.matrix$table[2,1]
rf.accuracy.sonar <- (tp + tn)/(tp+tn+fp+fn)
cat("Accuracy : " , accuracy)
rf.precision.sonar <- tp/(tp+fp)
cat("Precision : " , precision)
rf.ecall.sonar <- tp/(tp+fn)
cat("Recall : " , recall)
rf.fMeasure.sonar <- (2 * tp)/(2*tp + fp + fn)
cat("F1 measure : " , fMeasure)
```
Neural Model

```{r, CACHED = TRUE}
model <- train(train.data[,-61], train.data[,61],
                 method = "nnet",
                 trControl = trainControl(method = "cv", number = 10, summaryFunction = defaultSummary))
predictions.nnet <- predict(model, test.data[,-61])
results.matrix <- confusionMatrix(predictions.nnet , test.data$category)
tp <- results.matrix$table[1,1]
tn <- results.matrix$table[2,2]
fp <- results.matrix$table[1,2]
fn <- results.matrix$table[2,1]
nn.accuracy.sonar <- (tp + tn)/(tp+tn+fp+fn)
cat("Accuracy : " , accuracy)
nn.precision.sonar <- tp/(tp+fp)
cat("Precision : " , precision)
nn.recall.sonar <- tp/(tp+fn)
cat("Recall : " , recall)
nn.fMeasure.sonar <- (2 * tp)/(2*tp + fp + fn)
cat("F1 measure : " , fMeasure)
```
svmLinear
```{r, CACHED = TRUE}
model <- train(train.data[,-61], train.data[,61],
                 method = "svmLinear",
                 trControl = trainControl(method = "cv", number = 10, summaryFunction = defaultSummary))
predictions <- predict(model$finalModel, test.data[,-61])
results.matrix <- confusionMatrix(predictions, test.data$category)
tp <- results.matrix$table[1,1]
tn <- results.matrix$table[2,2]
fp <- results.matrix$table[1,2]
fn <- results.matrix$table[2,1]
svm.accuracy.sonar <- (tp + tn)/(tp+tn+fp+fn)
cat("Accuracy : " , accuracy)
svm.precision.sonar <- tp/(tp+fp)
cat("Precision : " , precision)
svm.recall.sonar <- tp/(tp+fn)
cat("Recall : " , recall)
svm.fMeasure.sonar <- (2 * tp)/(2*tp + fp + fn)
cat("F1 measure : " , fMeasure)
```
NB
```{r, CACHED = TRUE}
model <- train(train.data[,-61], train.data[,61],
                 method = "nb",
                 trControl = trainControl(method = "cv", number = 10, summaryFunction = defaultSummary))
predictions <- predict(model$finalModel, test.data[,-61])
results.matrix <- confusionMatrix(predictions$class , test.data$category)
tp <- results.matrix$table[1,1]
tn <- results.matrix$table[2,2]
fp <- results.matrix$table[1,2]
fn <- results.matrix$table[2,1]
nb.accuracy.sonar <- (tp + tn)/(tp+tn+fp+fn)
cat("Accuracy : " , accuracy)
nb.precision.sonar <- tp/(tp+fp)
cat("Precision : " , precision)
nb.recall.sonar <- tp/(tp+fn)
cat("Recall : " , recall)
nb.fMeasure.sonar <- (2 * tp)/(2*tp + fp + fn)
cat("F1 measure : " , fMeasure)
```
Boosting
```{r, CACHED = TRUE}
model <- AdaBoostM1(category~., data = train.data,
                 control = Weka_control(W = "J48"))
summary(model)
model_folds_eval <- evaluate_Weka_classifier(model, numFolds = 10)
model_folds_eval
```
Bagging
```{r}
model <- Bagging(category~., data = train.data,
                 control = Weka_control(W = "J48"))
summary(model)
model_folds_eval <- evaluate_Weka_classifier(model, numFolds = 10)
model_folds_eval
```
Load Hepatitis Data set and Heart Data set
```{r}
hepa.data <- read.csv("hepatitis.data", sep = ",")
#View(hepa.data)
colnames(hepa.data)[1] <- "category"
hepa.data[hepa.data == "?"] = NA
train_size <- floor(0.85 * nrow(hepa.data))

set.seed(123)
train_ind <- sample(seq_len(nrow(hepa.data)), size = train_size)

hepa.train.data <- hepa.data[train_ind, ]
hepa.test.data <- hepa.data[-train_ind, ]

heart.data <- read.csv("SPECT.train")

colnames(heart.data)[1] <- "category"
hepa.data[heart.data == "?"] = NA
train_size <- floor(0.85 * nrow(heart.data))

set.seed(123)
train_ind <- sample(seq_len(nrow(heart.data)), size = train_size)

heart.train.data <- heart.data[train_ind, ]
heart.test.data <- heart.data[-train_ind, ]
```
Random Forest
```{r, CACHED = TRUE}
model <- train(heart.train.data[,-1], heart.train.data[,1],
                 method = "rf",
                 trControl = trainControl(method = "repeatedcv", number = 10, repeats =10, summaryFunction = defaultSummary))
predictions <- predict(model$finalModel, heart.test.data)
results.matrix <- confusionMatrix(predictions , heart.test.data$category)
tp <- results.matrix$table[1,1]
tn <- results.matrix$table[2,2]
fp <- results.matrix$table[1,2]
fn <- results.matrix$table[2,1]
rf.accuracy.heart <- (tp + tn)/(tp+tn+fp+fn)
cat("Accuracy : " , accuracy)
rf.precision.heart <- tp/(tp+fp)
cat("Precision : " , precision)
rf.recall.heart <- tp/(tp+fn)
cat("Recall : " , recall)
rf.fMeasure.heart <- (2 * tp)/(2*tp + fp + fn)
cat("F1 measure : " , fMeasure)
```
Neural Model

```{r, CACHED = TRUE}
model <- train(heart.train.data[,-1], heart.train.data[,1],
                 method = "nnet",
                 trControl = trainControl(method = "repeatedcv", number = 10, repeats =10, summaryFunction = defaultSummary))
predictions.nnet <- predict(model, heart.test.data[,-1])
results.matrix <- confusionMatrix(predictions.nnet , heart.test.data$category)
tp <- results.matrix$table[1,1]
tn <- results.matrix$table[2,2]
fp <- results.matrix$table[1,2]
fn <- results.matrix$table[2,1]
nn.accuracy.heart <- (tp + tn)/(tp+tn+fp+fn)
cat("Accuracy : " , accuracy)
nn.precision.heart <- tp/(tp+fp)
cat("Precision : " , precision)
nn.recall.heart <- tp/(tp+fn)
cat("Recall : " , recall)
nn.fMeasure.heart <- (2 * tp)/(2*tp + fp + fn)
cat("F1 measure : " , fMeasure)
```
svmLinear
```{r, CACHED = TRUE}
model <- train(heart.train.data[,-1], heart.train.data[,1],
                 method = "svmLinear",
                 trControl = trainControl(method = "repeatedcv", number = 10, repeats =10, summaryFunction = defaultSummary))
predictions <- predict(model$finalModel, heart.test.data[,-1])
results.matrix <- confusionMatrix(predictions, heart.test.data$category)
tp <- results.matrix$table[1,1]
tn <- results.matrix$table[2,2]
fp <- results.matrix$table[1,2]
fn <- results.matrix$table[2,1]
svm.accuracy.heart <- (tp + tn)/(tp+tn+fp+fn)
cat("Accuracy : " , accuracy)
svm.precision.heart <- tp/(tp+fp)
cat("Precision : " , precision)
svm.recall.heart <- tp/(tp+fn)
cat("Recall : " , recall)
svm.fMeasure.heart <- (2 * tp)/(2*tp + fp + fn)
cat("F1 measure : " , fMeasure)
```
NB
```{r, CACHED = TRUE}
model <- train(heart.train.data[,-1], heart.train.data[,1],
                 method = "nb",
                 trControl = trainControl(method = "repeatedcv", number = 10, repeats =10, summaryFunction = defaultSummary))
predictions <- predict(model$finalModel, heart.test.data[,-1])
results.matrix <- confusionMatrix(predictions$class , heart.test.data$category)
tp <- results.matrix$table[1,1]
tn <- results.matrix$table[2,2]
fp <- results.matrix$table[1,2]
fn <- results.matrix$table[2,1]
nb.accuracy.heart <- (tp + tn)/(tp+tn+fp+fn)
cat("Accuracy : " , accuracy)
nb.precision.heart <- tp/(tp+fp)
cat("Precision : " , precision)
nb.recall.heart <- tp/(tp+fn)
cat("Recall : " , recall)
nb.fMeasure.heart <- (2 * tp)/(2*tp + fp + fn)
cat("F1 measure : " , fMeasure)
```
Accuracy Metric
```{r}
Name <- c("sonar", "hepatitis", "heart")
svm <- c(0,0,0)
nb <- c(0,0,0)
nnet <- c(0,0,0)
rforest <- c(0,0,0)
Acc_df <- data.frame(Name, svm, nb, nnet, rforest)
#View(Acc_df)
Acc_df[1,2] = svm.accuracy.sonar
Acc_df[1,3] = nb.accuracy.sonar
Acc_df[1,4] = nnet.accuracy.sonar
Acc_df[1,5] = rf.accuracy.sonar
Acc_df[3,2] = svm.accuracy.heart
Acc_df[3,3] = nb.accuracy.heart
Acc_df[3,4] = nn.accuracy.heart
Acc_df[3,5] = rf.accuracy.heart
View(Acc_df)
```
Precision Metric
```{r}
Name <- c("sonar", "hepatitis", "heart")
svm <- c(0,0,0)
nb <- c(0,0,0)
nnet <- c(0,0,0)
rforest <- c(0,0,0)
Pr_df <- data.frame(Name, svm, nb, nnet, rforest)

Pr_df[1,2] = svm.precision.sonar
Pr_df[1,3] = nb.precision.sonar
Pr_df[1,4] = nnet.precision.sonar
Pr_df[1,5] = rf.precision.sonar
Pr_df[3,2] = svm.precision.heart
Pr_df[3,3] = nb.precision.heart
Pr_df[3,4] = nn.precision.heart
Pr_df[3,5] = rf.precision.heart
View(Pr_df)
```
Recall Metric
```{r}
Name <- c("sonar", "hepatitis", "heart")
svm <- c(0,0,0)
nb <- c(0,0,0)
nnet <- c(0,0,0)
rforest <- c(0,0,0)
Recall_df <- data.frame(Name, svm, nb, nnet, rforest)

Recall_df[1,2] = svm.recall.sonar
Recall_df[1,3] = nb.recall.sonar
Recall_df[1,4] = nnet.recall.sonar
Recall_df[1,5] = rf.recall.sonar
Recall_df[3,2] = svm.recall.heart
Recall_df[3,3] = nb.recall.heart
Recall_df[3,4] = nn.recall.heart
Recall_df[3,5] = rf.recall.heart
View(Recall_df)
```
f Measure Metric
```{r}
Name <- c("sonar", "hepatitis", "heart")
svm <- c(0,0,0)
nb <- c(0,0,0)
nnet <- c(0,0,0)
rforest <- c(0,0,0)
f_df <- data.frame(Name, svm, nb, nnet, rforest)

f_df[1,2] = svm.fMeasure.sonar
f_df[1,3] = nb.fMeasure.sonar
f_df[1,4] = nnet.fMeasure.sonar
f_df[1,5] = rf.fMeasure.sonar
f_df[3,2] = svm.fMeasure.heart
f_df[3,3] = nb.fMeasure.heart
f_df[3,4] = nn.fMeasure.heart
f_df[3,5] = rf.fMeasure.heart
View(f_df)
```